http:
  port: 8061
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  user:
    host: localhost
    paths: ['/user', '/user/*']
  post:
    host: localhost
    paths: ['/post', '/post/*']
  aggregator:
    host: localhost
    paths: ['/user-post', '/user-post/*']
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  userService:
    url: 'https://jsonplaceholder.typicode.com/users'
  postService:
    url: 'https://jsonplaceholder.typicode.com/posts'
  aggregatorService:
    url: 'http://localhost:8080/users-posts'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  userPipeline:
    apiEndpoints:
      - user
    policies:
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
  postPipeline:
    apiEndpoints:
      - post
    policies:
      - proxy:
          - action:
              serviceEndpoint: postService
              changeOrigin: true

